/**
 * GENERATED by tools/verify-atlas.js. Do not edit by hand.
 *
 * Empty until the "6. Verify atlas counties" workflow has run. It is committed
 * empty rather than left absent so that counties.js can import it
 * unconditionally -- a missing module is a Worker that will not boot, and the
 * first person to pull this branch should get a running app, not a broken
 * import waiting on a workflow nobody told them about.
 */

const ATLAS_COUNTIES = {};

export { ATLAS_COUNTIES };
